// docs/angular/components/Demos/Pokeapi/Pokeapi.component.ts
import { Component, ChangeDetectionStrategy, Input, OnInit, ChangeDetectorRef } from "@angular/core"

import "self/common/styles/Pokeapi.css"

import { Item, cachedFetch } from "./models"

@Component({
    selector: "PokeApiComponent",
    template: `
        <div style="position: relative;">
            <div style="text-align: center; margin: 10px;">
                <div>
                    <a href="https://pokeapi.co/" target="_blank" rel="noopener noreferrer">
                        <img src="https://avatars3.githubusercontent.com/u/19692032?v=4&s=200"
                            alt="Pokéapi logo" style="width: 50px; filter: drop-shadow(0 0 2px #444);" />
                    </a>
                </div>
                <h5>Pokémon API crawler</h5>
                <div>
                    <button (click)="init()" class="PokeapiButton">Reset</button>
                </div>
            </div>
            <TreeView
                [model]="data"
                category="__children"
                [(selection)]="selection"
                [displayComponent]="displayComponent"
                [strategies]="conf.strategies"
                [css]="conf.css"
                [disabled]="conf.disabled"
                [search]="conf.search"></TreeView>
            <div
                class="PokeapiLoadMore center-text"
                [ngClass]="{ loading: loading }"
                [style]="'display:' + loadUrl ? 'block' : 'none'"
                (click)="loadMorePokemons()">
                <i class="fa fa-spinner" *ngIf="loading"></i>
                <span *ngIf="!loading">Show more pokémons</span>
            </div>
        </div>
    `,
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class PokeApiComponent {

    conf = {
        strategies: { fold: [ "opener-control", _ => !_.__subsection ], click: ["toggle-fold"]},
        css: { TreeView: "PokeapiDemo" },
        disabled: _ => _.__children && _.__children instanceof Array && _.__children.length === 0,
        search: input => item => item.name && item.name.startsWith(input)
    }
    data = []
    selection = []
    loading = false
    loadUrl = "https://pokeapi.co/api/v2/pokemon"
    displayComponent(item) { return item.display() }

    constructor(private cdRef: ChangeDetectorRef){}

    ngOnInit() {
        this.init()
    }

    init() {
        this.loadUrl = "https://pokeapi.co/api/v2/pokemon"
        this.loadPokemons().then(_ => {
            this.data = _
            this.cdRef.markForCheck()
        })
    }

    loadPokemons() {
        if(!this.loadUrl) return
        this.loading = true
        return cachedFetch(this.loadUrl)
            .then(json => {
                this.loadUrl = json.next
                this.loading = false
                return json.results.map(i => ({
                    ...i,
                    display: () => PokemonDisplayComponent,
                    __children: () => cachedFetch(i.url).then(json => [new Item(json)])
                }))
            })
            .catch(err => this.loading = false)
    }
    loadMorePokemons() {
        if(this.loading) return
        this.loadPokemons().then(_ => {
            this.data = [ ...this.data, ..._ ]
            this.cdRef.markForCheck()
        })
    }
}

@Component({
    template: "{{item.name}}"
})
export class PokemonDisplayComponent { item }

// docs/react/components/Demos/Pokeapi/Pokeapi.js
import React from "react"

import "self/common/styles/Pokeapi.css"

import { TreeView } from "bosket/react"
import { css } from "bosket/tools"
import { Item, cachedFetch } from "./models"

export class Pokeapi extends React.PureComponent {

    state = {
        data: [],
        selection: [],
        loading: false
    }

    conf = {
        strategies: { fold: [ "opener-control", _ => !_.__subsection ], click: ["toggle-fold"]},
        css: { TreeView: "PokeapiDemo" },
        disabled: _ => _.__children && _.__children instanceof Array && _.__children.length === 0,
        search: input => item => item.name && item.name.startsWith(input)
    }

    loadUrl = "https://pokeapi.co/api/v2/pokemon"

    componentDidMount() {
        this.init()
    }

    init() {
        this.loadUrl = "https://pokeapi.co/api/v2/pokemon"
        this.loadPokemons().then(_ => this.setState({ data: _ }))
    }

    loadPokemons() {
        if(!this.loadUrl) return
        this.setState({ loading: true })
        return cachedFetch(this.loadUrl)
            .then(json => {
                this.loadUrl = json.next
                this.setState({ loading: false })
                return json.results.map(i => ({
                    ...i,
                    display: _ => _.name,
                    __children: () => cachedFetch(i.url).then(json => [new Item(json)])
                }))
            })
            .catch(err => this.setState({ loading: false }))
    }

    render = () =>
        <div style={{ position: "relative " }}>
            <div style={{ textAlign: "center", margin: "10px" }}>
                <div>
                    <a href="https://pokeapi.co/" target="_blank" rel="noopener noreferrer">
                        <img src="https://avatars3.githubusercontent.com/u/19692032?v=4&s=200"
                            alt="Pokéapi logo" style={{ width: "50px", filter: "drop-shadow(0 0 2px #444)" }}/>
                    </a>
                </div>
                <h5>Pokémon API crawler</h5>
                <div>
                    <button onClick={ _ => this.init(_) } className="PokeapiButton">Reset</button>
                </div>
            </div>
            <TreeView
                model={ this.state.data }
                category="__children"
                display={ _ => _.display(_)  }
                selection={ this.state.selection }
                onSelect={ _ => this.setState({ selection: _ }) }
                strategies={ this.conf.strategies }
                css={ this.conf.css }
                disabled={ this.conf.disabled }
                search={ this.conf.search }/>
            <div
                className={ "PokeapiLoadMore center-text " + css.classes({ loading: this.state.loading })  }
                style={{ display: this.loadUrl ? "block" : "none" }}
                onClick={ ev => !this.state.loading && this.loadPokemons().then(_ => this.setState({ data: [ ...this.state.data, ..._ ]})) }>
                { this.state.loading ? <i className="fa fa-spinner fa-2x"></i> : <span>Show more pokémons</span> }
            </div>
        </div>

}
