// docs/angular/plan/Planner.component.ts
import { Component, Input, ChangeDetectionStrategy, ComponentFactoryResolver,
    SimpleChanges, Type, ViewChild, ElementRef, ViewContainerRef, ChangeDetectorRef } from "@angular/core"

import { css } from "bosket/tools"
import { DisplayComponent } from "bosket/angular"

import "self/common/styles/Planner.css"

type Plan = {
    title: string,
    content?: Type<any>,
    subs?: Plan[]
}

@Component({
    selector: "planner-content",
    template:`
        <div [class]="depth === 1 ? 'chapter' : 'planner-section'">
            <h1 *ngIf="depth === 1" [id]="id()" class="Planner heading">
                <span>{{ plan.title }}</span>
                <span class="icons">
                    <a [href]="'#' + id() "><i class="fa fa-link"></i></a>
                    <a *ngIf="plan.editLink" [href]="plan.editLink" target="_blank" rel=" noopener noreferrer">
                        <i class="fa fa-pencil"></i>
                    </a>
                </span>
            </h1>
            <h2 *ngIf="depth === 2" [id]="id()" class="Planner heading">
                <span>{{ plan.title }}</span>
                <span class="icons">
                    <a [href]="'#' + id() "><i class="fa fa-link"></i></a>
                    <a *ngIf="plan.editLink" [href]="plan.editLink" target="_blank" rel=" noopener noreferrer">
                        <i class="fa fa-pencil"></i>
                    </a>
                </span>
            </h2>
            <h3 *ngIf="depth === 3" [id]="id()" class="Planner heading">
                <span>{{ plan.title }}</span>
                <span class="icons">
                    <a [href]="'#' + id() "><i class="fa fa-link"></i></a>
                    <a *ngIf="plan.editLink" [href]="plan.editLink" target="_blank" rel=" noopener noreferrer">
                        <i class="fa fa-pencil"></i>
                    </a>
                </span>
            </h3>
            <h4 *ngIf="depth === 4" [id]="id()" class="Planner heading">
                <span>{{ plan.title }}</span>
                <span class="icons">
                    <a [href]="'#' + id() "><i class="fa fa-link"></i></a>
                    <a *ngIf="plan.editLink" [href]="plan.editLink" target="_blank" rel=" noopener noreferrer">
                        <i class="fa fa-pencil"></i>
                    </a>
                </span>
            </h4>
            <h5 *ngIf="depth === 5" [id]="id()" class="Planner heading">
                <span>{{ plan.title }}</span>
                <span class="icons">
                    <a [href]="'#' + id() "><i class="fa fa-link"></i></a>
                    <a *ngIf="plan.editLink" [href]="plan.editLink" target="_blank" rel=" noopener noreferrer">
                        <i class="fa fa-pencil"></i>
                    </a>
                </span>
            </h5>
            <h6 *ngIf="depth === 6" [id]="id()" class="Planner heading">
                <span>{{ plan.title }}</span>
                <span class="icons">
                    <a [href]="'#' + id() "><i class="fa fa-link"></i></a>
                    <a *ngIf="plan.editLink" [href]="plan.editLink" target="_blank" rel=" noopener noreferrer">
                        <i class="fa fa-pencil"></i>
                    </a>
                </span>
            </h6>
            <p *ngIf="depth > 6" [id]="id()" class="Planner heading">
                <span>{{ plan.title }}</span>
                <span class="icons">
                    <a [href]="'#' + id() "><i class="fa fa-link"></i></a>
                    <a *ngIf="plan.editLink" [href]="plan.editLink" target="_blank" rel=" noopener noreferrer">
                        <i class="fa fa-pencil"></i>
                    </a>
                </span>
            </p>
            <div #content></div>
            <div *ngIf="plan.subs">
                <div *ngFor="let s of plan.subs">
                    <planner-content [plan]="s" [prefix]="prefix ? prefix+'#'+plan.title : plan.title" [depth]="depth + 1"></planner-content>
                </div>
            </div>
        </div>`,
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class PlannerContent {
    @Input() plan: Plan
    @Input() prefix: string = ""
    @Input() depth: number = 1
    @ViewChild("content", { read: ViewContainerRef } ) content : ViewContainerRef

    constructor(private _componentFactoryResolver: ComponentFactoryResolver, private _cdRef: ChangeDetectorRef) { }

    ngOnChanges(changes: SimpleChanges) {
        this.refresh()
    }
    ngAfterViewInit() {
        this.refresh()
    }

    refresh() {
        if(!this.plan || !this.content || !this.plan.content) return

        this.content.clear()
        let componentFactory = this._componentFactoryResolver.resolveComponentFactory(this.plan.content)
        let componentRef = this.content.createComponent(componentFactory)

        setTimeout(() => this._cdRef.markForCheck(), 0)
    }

    id() {
        return this.prefix ? `${this.prefix}#${this.plan.title}` : this.plan.title
    }
}

@Component({
    template: `<a [href]="href()">{{ item.title }}</a>`,
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class PlannerInjector implements DisplayComponent<Plan> {
    @Input() item : Plan
    @Input() inputs: any

    href() {
        return `${this.inputs.ancestors.map(a => "#" + a.title).join("")}#${this.item.title}`
    }
}

// <aside #sidePanel [class]="'Planner side-panel ' + css.classes({ opened: this.state.opened })">
@Component({
    selector: "planner",
    template: `
        <div class="Planner">
            <div class="Planner opener" #opener>
                <i class="fa" [ngClass]="{
                    'fa-bars': !opened,
                    'fa-times': opened
                }"></i>
            </div>
            <aside #sidePanel class="Planner side-panel" [ngClass]="{ opened: opened }">
                <div><h1>Table of contents</h1></div>
                <TreeView
                    [model]="plan"
                    [css]="{ TreeView: 'PlannerTree' }"
                    category="subs"
                    [(selection)]="selection"
                    [strategies]="{ selection: ['ancestors'], fold: [ foldDepth(), 'not-selected', 'no-child-selection' ]}"
                    noOpener="true"
                    [displayComponent]="component">
                </TreeView>
            </aside>
            <div #content class="Planner content">
                <div *ngFor="let p of plan">
                    <planner-content [plan]="p"></planner-content>
                </div>
            </div>
        </div>
    `,
    changeDetection: ChangeDetectionStrategy.OnPush,
    host: {
        '(document:scroll)': 'onDocumentScroll($event)',
        '(document:click)': 'onDocumentClick($event)'
    }
})
export class Planner {
    @Input() plan : Object
    @Input() maxDepth : number = 0
    @Input() sticky : boolean = false
    @ViewChild("sidePanel") sidePanel : ElementRef
    @ViewChild("content") content : ElementRef
    @ViewChild("opener") opener: ElementRef

    public selection = []
    public foldDepth = () => {
        const max = this.maxDepth
        return function() {
            return this.inputs.get().depth >= max
        }
    }
    public css = css
    public component = PlannerInjector
    public opened = false
    private ticking = false
    private stickTick = false
    private sticking = false

    private onDocumentScroll(ev) {
        if(!this.ticking) {
            window.requestAnimationFrame(() => {
                const result = []
                const loop = (arr, acc = []) => {
                    for(let i = 0; i < arr.length; i++) {
                        const elt = arr[i]
                        const domElt = document.getElementById(acc.length > 0 ? acc.join("#") + "#" + elt.title : elt.title)
                        if(domElt && domElt.parentElement &&
                                domElt.parentElement.getBoundingClientRect().top <= 50 &&
                                domElt.parentElement.getBoundingClientRect().bottom > 10) {
                            result.push(elt)
                            if(elt.subs)
                                loop(elt.subs, [ ...acc, elt.title ])
                            break
                        }
                    }
                }
                loop(this.plan)
                const newHash = "#" + result.map(_ => _.title).join("#")
                if(newHash !== window.location.hash) {
                    this.selection = result
                    window.history && window.history.replaceState(
                        {},
                        document.title,
                        "#" + result.map(_ => _.title).join("#"))
                }
                // Prevents safari security exception (SecurityError (DOM Exception 18): Attempt to use history.replaceState() more than 100 times per 30.000000 seconds)
                setTimeout(() => this.ticking = false, 100)
            })
            this.ticking = true
        }
        if(this.sticky && !this.stickTick) {
            if(this.content.nativeElement.getBoundingClientRect().top > 0) {
                window.requestAnimationFrame(() => {
                    this.sidePanel.nativeElement.style.position = "absolute"
                    this.sidePanel.nativeElement.style.top = ""
                    this.sticking = false
                    this.stickTick = false
                })
            } else {
                window.requestAnimationFrame(() => {
                    this.sidePanel.nativeElement.style.position = "fixed"
                    this.sidePanel.nativeElement.style.top = "0px"
                    this.sticking = true
                    this.stickTick = false
                })
            }
            this.stickTick = true
        }
    }
    private onDocumentClick(ev) {
         if(!(ev.target instanceof HTMLElement)) return
            if(this.opener && this.opener.nativeElement.contains(ev.target)) {
                this.opened = !this.opened
            } else if(this.opened && this.sidePanel && !this.sidePanel.nativeElement.contains(ev.target))
                this.opened = false
    }
}

// docs/react/components/Planner/Planner.js

// @flow

import React from "react"
import "self/common/styles/Planner.css"

import { TreeView } from "bosket/react"
import { css } from "bosket/tools"
import { withListener, combine } from "bosket/react/traits"

const headerLevel = (depth, prefix, item) => {
    const id = prefix ? `${prefix}#${item.title}` : item.title
    const editLink = !item.editLink ? null : <a href={ item.editLink } target="_blank" rel=" noopener noreferrer"><i className="fa fa-pencil"></i></a>
    return React.createElement(
        "h" + depth,
        {
            id: id,
            className: "Planner heading"
        },
        <span>{ item.title }</span>,
        <span className="icons">
            <a href={ "#" + id }><i className="fa fa-link"></i></a>
            { editLink }
        </span>
    )
}

const processContent = (plan, parentPrefix = "", depth = 1) => {
    if(!plan && plan.length < 1)
        return null

    return plan.map(item =>
        <div className={ depth === 1 ? "chapter" : "planner-section" } key={ item.title }>
            { headerLevel(depth, parentPrefix, item) }
            { item.content }
            { item.subs && item.subs.length > 0 ?
                processContent(item.subs, parentPrefix ? `${parentPrefix}#${item.title}` : item.title, depth + 1) :
                null
            }
        </div>
    )
}

type Plan = {
    title: string,
    content?: React$Element<*>,
    subs?: Plan[]
}

export const Planner = combine(
    withListener({ propName: "clickListener", autoMount: true }),
    withListener({ eventType: "scroll", propName: "scrollListener", autoMount: true, regulate: true }),
    withListener({ eventType: "scroll", propName: "offsetListener", autoMount: true, regulate: true })
)(class extends React.PureComponent<*, *> {

    props : {
        plan: Plan[],
        clickListener?: Object,
        scrollListener?: Object,
        offsetListener?: Object,
        maxDepth?: number,
        sticky?: boolean
    }

    state = {
        css: { TreeView: "PlannerTree" },
        category: "subs",
        selection: [],
        display: (item, inputs) => <a href={ `${inputs.ancestors.map(a => "#" + a.title).join("")}#${item.title}` }>{ item.title }</a>,
        onSelect: _ => { if(_.length > 0) { this.setState({ selection: _ }) } },
        strategies: {
            selection: ["ancestors"],
            fold: [ "max-depth", "not-selected", "no-child-selection" ]
        },
        noOpener: true,
        opened: false
    }
    opener: HTMLElement
    sidePanel: HTMLElement
    content: HTMLElement
    ticking = false
    sticking = false

    componentDidMount = () => {
        this.props.clickListener && this.props.clickListener.subscribe((ev: Event) => {
            if(!(ev.target instanceof HTMLElement)) return
            if(this.opener && this.opener.contains(ev.target)) {
                this.setState({ opened: !this.state.opened })
            } else if(this.state.opened && this.sidePanel && !this.sidePanel.contains(ev.target))
                this.setState({ opened: false })
        })

        this.props.scrollListener && this.props.scrollListener.subscribe((ev: Event, end: void => void) => {
            const result = []
            const loop = (arr, acc = []) => {
                for(let i = 0; i < arr.length; i++) {
                    const elt = arr[i]
                    const domElt = document.getElementById(acc.length > 0 ? acc.join("#") + "#" + elt.title : elt.title)
                    if(domElt && domElt.parentElement &&
                            domElt.parentElement.getBoundingClientRect().top <= 50 &&
                            domElt.parentElement.getBoundingClientRect().bottom > 10) {
                        result.push(elt)
                        if(elt.subs)
                            loop(elt.subs, [ ...acc, elt.title ])
                        break
                    }
                }
            }
            loop(this.props.plan)
            const newHash = "#" + result.map(_ => _.title).join("#")
            if(newHash !== (window.location.hash || "#")) {
                this.setState({ selection: result })
                window.history && window.history.replaceState(
                    {},
                    document.title,
                    "#" + result.map(_ => _.title).join("#"))
            }

            // Prevents safari security exception (SecurityError (DOM Exception 18): Attempt to use history.replaceState() more than 100 times per 30.000000 seconds)
            setTimeout(() => end(), 100)
        })

        if(this.props.sticky) {
            this.props.offsetListener && this.props.offsetListener.subscribe((ev: Event, end: void => void) => {
                if(this.content.getBoundingClientRect().top > 0) {
                    this.sidePanel.style.position = "absolute"
                    this.sidePanel.style.top = ""
                    this.sticking = false
                    end()
                } else {
                    this.sidePanel.style.position = "fixed"
                    this.sidePanel.style.top = "0px"
                    this.sticking = true
                    end()
                }
            })
        }
    }

    render() {
        return !this.props.plan ? null :
            <div className="Planner">
                <div className="Planner opener" ref={ ref => { if(ref) this.opener = ref } }>
                    <i className={ "fa " + css.classes({
                        "fa-bars": !this.state.opened,
                        "fa-times": this.state.opened
                    })}></i>
                </div>
                <aside ref={ ref => { if(ref) this.sidePanel = ref } } className={ "Planner side-panel " + css.classes({ opened: this.state.opened }) }>
                    <div><h1>Table of contents</h1></div>
                    <TreeView model={ this.props.plan } maxDepth={ this.props.maxDepth } { ...this.state }></TreeView>
                </aside>
                <div ref={ ref => { if(ref) this.content = ref } } className="Planner content">
                    { processContent(this.props.plan) }
                </div>
            </div>
    }
})
