// docs/vue/components/App.vue
<template>

    <div class="App">
        <Planner :plan="plan" :maxDepth="1" :sticky="true"></Planner>
    </div>

</template>

<script>

    import "self/common/styles/App.css"

    import Vue from "vue"

    import plan from "../plan"

    import Planner from "./Planner"
    Vue.component("Planner", Planner)

    export default {
        data: () => ({
            plan: plan
        })
    }

</script>

// docs/react/components/App/App.js
// @flow

import React from "react"

import "self/common/styles/App.css"

import { Planner } from "self/react/components/Planner/Planner"
import plan from "self/react/plan"

export class App extends React.PureComponent {
    componentDidMount() {
        if(window.location.hash) {
            const elt = document.getElementById(window.location.hash.substring(1))
            if(elt) elt.scrollIntoView()
        }
    }

    render() {
        return (
            <div className="App">
                <Planner plan={ plan } maxDepth={ 1 } sticky={ true }></Planner>
            </div>
        )
    }
}
