// docs/angular/components/App/App.component.ts
import { Component } from "@angular/core"
import plan from "self/angular/plan/plan"

import "self/common/styles/App.css"

@Component({
    selector: "div#framework-root",
    template: `
        <div class="App">
            <planner [plan]="plan" [maxDepth]="1" [sticky]="true"></planner>
        </div>
    `
})
export class AppComponent {
    public plan = plan
}

// docs/vue/components/App.vue
<template>

    <div class="App">
        <Planner :plan="plan" :maxDepth="1" :sticky="true"></Planner>
    </div>

</template>

<script>

    import "self/common/styles/App.css"

    import Vue from "vue"

    import plan from "../plan"

    import Planner from "./Planner"
    Vue.component("Planner", Planner)

    export default {
        data: () => ({
            plan: plan
        })
    }

</script>
