// demo/react/components/App/App.js
import "./App.css"
import React from "react"

import * as sectionsImport from "../Sections"

const sections = (() => {
    const res = []
    for(const section in sectionsImport) {
        res.push(sectionsImport[section])
    }
    return res
})()

export const App = prop =>
     <div className="App">
        <p>This page is rendered using react 15.5.4</p>
        <div className="components-container">
            { sections.map((Section, i) => <Section key={i}></Section>) }
        </div>
    </div>

// docs/angular/components/App/App.component.ts
import { Component } from "@angular/core"
//import * as sections from "../Sections"

@Component({
    selector: "div#framework-root",
    template: `
        <div class="App">
            <p>This page is rendered using angular 4.1.2</p>
            <div class="components-container">
                <itemtree-section></itemtree-section>
            </div>
        </div>
    `,
    styles: [`
        .App {
            /* text-align: center; */
        }

        .App-intro {
            font-size: large;
        }
    `]
})
export class AppComponent {}
