// docs/angular/components/Demos/TreeView/TreeViewDemo.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core"

// Css style
import "./TreeViewDemo.css"

// Data model
import initialModel from "self/common/models/TreeViewModel"

// Bosket imports
import { DisplayComponent } from "@bosket/angular"
import { dragndrop } from "@bosket/core"

@Component({
    selector: "treeview-demo",
    template: `
        <!-- We render the TreeView here -->
        <TreeView
            [model]="model"
            [category]="category"
            [(selection)]="selection"
            [sort]="sort"
            [key]="key"
            [search]="search"
            [strategies]="strategies"
            [dragndrop]="dragndrop"
            [displayComponent]="displayComponent"
            [css]="css"
            (onDrop)="onDrop($event)"
            (onDrag)="onDrag($event)">
        </TreeView>`
})
export class TreeViewDemo {

    // Load the drag image once on component creation
    private dragImage: HTMLImageElement
    constructor(){
        this.dragImage = new Image()
        this.dragImage.src = "../assets/drag-image.png"
    }

    // Model mapping
    model: Object[] = initialModel
    // Each object of the model has a property "items" containing the children
    category = "items"
    // We enhance the ouput by passing a custom component which will wrap items
    displayComponent = ItemDisplay
    // Unique identifier used by angular to "track" changes on list updates
    key = (index, item) => item.label
    // The sorting function
    sort = (a, b) => a.label.localeCompare(b.label)
    // Enables the search bar + defines the search algorithm
    search = input => i => i.label.match(new RegExp(`.*${ input }.*`, "gi"))
    // The selected items list, which is here defined in the parent component (hence the double binding)
    @Input()
    get selection() { return this._selection }
    set selection(s) { this._selection = s; this.selectionChange.emit(s) }
    private _selection = []
    @Output() selectionChange = new EventEmitter<any>()
    strategies = {
        // Strategies performed on click, selection & fold
        // select on click
        click: ["select"],
        // "modifiers" means that we single/multi select depending on which keyboard modifiers are active
        selection: ["modifiers"],
        // "opener-control" allows the opener arrow to control the folding
        fold: ["opener-control"]
    }
    // Customize css class
    css = { TreeView: "TreeViewDemo" }
    // Drag'n'drop configuration
    dragndrop = {
        // Uses the "selection" preset (drag/drop the selected item(s))
        ...dragndrop.selection(() => this.model, m => this.model = m),
        // Restrain the drop zone to nodes with children only (and root node)
        droppable: _ => !_ || _.items && _.items instanceof Array
    }
    onDrop = ({target, event, inputs}) => this.dragndrop.drop(target, event, inputs)
    onDrag = ({target, event, inputs}) => {
        event.dataTransfer.setDragImage(this.dragImage, 0, 0)
        event.dataTransfer.setData("application/json", JSON.stringify(this.selection))
    }
}

// This component wraps items within an anchor tag
@Component({
    template:`<a>{{ item.label }}</a>`
})
export class ItemDisplay implements DisplayComponent<{ label }> {
    // Injected item
    @Input() item : { label }
}

// docs/react/components/Demos/TreeView/TreeViewDemo.js
// @flow

import React from "react"

// Bosket imports
import { TreeView } from "bosket/react"
import { string } from "bosket/tools"
import { dragndrop } from "bosket/core/dragndrop"

// Css
import "./TreeViewDemo.css"

// Model
import model from "self/common/models/TreeViewModel"

export class TreeViewDemo extends React.PureComponent {

    // Load the drag image once on component creation.
    constructor(props: { selection: Object[], update: Object[] => void }) {
        super(props)
        this.dragImage = new Image()
        this.dragImage.src = "../assets/drag-image.png"
    }
    dragImage: Image

    // The TreeView rendering
    render = () =>
        <TreeView
            selection={ this.props.selection }
            { ...this.state }>
        </TreeView>

    // The state is passed down to the TreeView.

    // Usually the state object is much shorter.
    // Here we deliberately set a lot of properties for the sake of the example.

    state = {
        // Data model
        model: model,
        // Property of the model containing children
        category: "items",
        // On selection, update the selection array in the parent component
        onSelect: function(items) {
            this.props.update(items)
        }.bind(this),
        // Custom display (with an anchor tag)
        display: (item: Object) => <a>{ item.label }</a>,
        // Alphabetical sort
        sort: (a: Object, b: Object) => a.label.localeCompare(b.label),
        // Unique identifier using an item name
        key: (item: Object) => item.label,
        // Search bar algorithm
        search: (input: string) => (i: Object) => string(i.label).contains(input),
        strategies: {
            // Use keyboard modifiers
            selection: ["modifiers"],
            click: [],
            // Use the opener to control element folding
            fold: ["opener-control"]
        },
        // Custom css root class name
        css: { TreeView: "TreeViewDemo" },
        // Transitions using react transition group
        transition: {
            transitionName: "TreeViewDemoTransition",
            transitionEnterTimeout: 300,
            transitionLeaveTimeout: 300
        },
        dragndrop: {
            // Use the "selection" drag and drop preset
            ...dragndrop.selection(() => this.state.model, m => this.setState({ model: m })),
            // Add a custom image on drag
            drag: (_, event) => {
                event.dataTransfer.setDragImage(this.dragImage, 0, 0)
                event.dataTransfer && event.dataTransfer.setData("application/json", JSON.stringify(this.props.selection))
            },
            // Drop only on categories or root (excluding asynchronous promises)
            droppable: _ => !_ || _.items && _.items instanceof Array
        }
    }
}
