// docs/angular/plan/introduction/IntroductionDemos.component.ts
import { Component } from "@angular/core"

import "self/common/styles/IntroductionDemos.css"

@Component({
    selector: "IntroductionDemos",
    template: `
         <div class="IntroductionDemos">
            <div class="center-text">
                <span class="button-row">
                    <button *ngFor="let d of demos" (click)="demo = d" [ngClass]="{ selected: d === demo }">
                        {{ d }}
                    </button>
                </span>
            </div>
            <ComponentDemo [files]="getFiles(demo)" [ngSwitch]="demo">
                <ChuckNorrisComponent *ngSwitchCase="'ChuckNorris'"></ChuckNorrisComponent>
                <PokeApiComponent *ngSwitchCase="'Pokeapi'"></PokeApiComponent>
                <HackerNewsComponent *ngSwitchCase="'HackerNews'"></HackerNewsComponent>
            </ComponentDemo>
        </div>
    `
})
export class IntroductionDemosComponent {
    demos = [ "HackerNews", "Pokeapi", "ChuckNorris" ]
    demo = this.demos[0]
    getFiles(demo) {
        return [
            `./components/Demos/${demo}/${demo}.component.ts`,
            `../common/styles/${demo}.css`,
            `./components/Demos/${demo}/models.ts`
        ]
    }
}

// docs/react/plan/introduction/IntroductionDemos.js
import React from "react"

import "self/common/styles/IntroductionDemos.css"

import { ComponentDemo } from "self/react/components/ComponentDemo/ComponentDemo"
import { ChuckNorris } from "self/react/components/Demos/ChuckNorris/ChuckNorris"
import { HackerNews } from "self/react/components/Demos/HackerNews/HackerNews"
import { Pokeapi } from "self/react/components/Demos/Pokeapi/Pokeapi"

export class IntroductionDemos extends React.PureComponent<*, *> {

    demos = [ "HackerNews", "Pokeapi", "ChuckNorris" ]
    state = { demo: this.demos[0] }

    renderDemo() {
        const Component =
            this.state.demo === "ChuckNorris" ? ChuckNorris :
                this.state.demo === "HackerNews" ? HackerNews :
                    this.state.demo === "Pokeapi" ? Pokeapi :
                        null

        const files = [
            `./components/Demos/${this.state.demo}/${this.state.demo}.js`,
            `../common/styles/${this.state.demo}.css`,
            `./components/Demos/${this.state.demo}/models.js`
        ]

        return (
            <ComponentDemo files={ files }>
                <Component />
            </ComponentDemo>
        )
    }

    renderButtons() {
        return this.demos.map(demo =>
            <button onClick={ ev => this.setState({ demo: demo }) } key={ demo } className={ this.state.demo === demo ? "selected" : "" }>
                { demo }
            </button>)
    }

    render = () =>
        <div className="IntroductionDemos">
            <div className="center-text">
                <span className="button-row">{ this.renderButtons() }</span>
            </div>
            { this.renderDemo() }
        </div>
}
